package srdc.smartcds.model

object UKBiobankFeatures {
  final val AGE = "21003"
  final val IMD_EMPLOYMENT_SCORE = "imd-employment-score"
  final val IMD_HEALTH_SCORE = "imd-health-score"
  final val ACCOMMODATION = "680"
  final val EMPLOYMENT = "6142"
  final val QUALIFICATION = "6138"
  final val WORRIER_FEELINGS = "1980"
  final val MOOD_SWING = "1920"
  final val FED_UP_FEELINGS = "1960"
  final val LONELINESS = "2020"
  final val MISERABLENESS = "1930"
  final val NERVES = "2010"
  final val SENSITIVITY = "1950"
  final val BMI = "21001"
  final val WEIGHT = "21002"
  final val HEIGHT = "50"
  final val WAIST_CIRCUMFERENCE = "48"
  final val HIP_CIRCUMFERENCE = "49"
  final val SYSTOLIC_BLOOD_PRESSURE = "sbp"
  final val DIASTOLIC_BLOOD_PRESSURE = "dbp"
  final val BODY_FAT_PERCENTAGE = "23099"
  final val SLEEP = "1160"
  final val GETTING_UP = "1170"
  final val NAP = "1190"
  final val INSOMNIA = "1200"
  final val COFFEE_TYPE = "1508"
  final val ALCOHOL_DRINKER_STATUS = "20117"
  final val SMOKING_STATUS = "20116"
  final val TOBACCO_SMOKING = "1239"
  final val MOTHER_ILLNESS_1 = "20110_1"
  final val MOTHER_ILLNESS_2 = "20110_2"
  final val SIBLING_ILLNESS_1 = "20111_1"
  final val DENTAL_PROBLEMS = "6149"
  final val FRACTURED_BONES = "2463"
  final val HEARING_DIFFICULTY = "2247"
  final val PAIN = "6159"
  final val HIGH_LIGHT_SCATTER_RETICULOCYTE_PCT = "high-light-scatter"
  final val CRP = "30710"
  final val CHOLESTEROL = "30690"
  final val CYSTATIN_C = "cystatin"
  final val GAMMA_GLUTAMYLTRANSFERASE = "gamma-gt"
  final val HBA1C = "30750"
  final val LDL = "ldl"
}
